CREATE PROC FI_SP_PesqBeneficiario
	@IdCliente bigint
AS
BEGIN

	IF(ISNULL(@IdCliente,0) = 0)
		SELECT * FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT * FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IdCliente
		
END